name: Pipeline App CI/CD 

on: 
  push:
    branches:
      - main

permissions:
  id-token: write  
  contents: read

jobs:
  job1:
    name: build_ecr
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::547320736290:role/github-actions-ecr-full-acsses
          aws-region: eu-north-1

      - name: Login Amazon ECR and Setup ECR Private Repository
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build, Tag, Push Image to Amazon ECR
        run: | 
          docker build -t mywebsite:v1.0 . 
          docker tag mywebsite:v1.0 547320736290.dkr.ecr.eu-north-1.amazonaws.com/bar:v1.0
          docker push 547320736290.dkr.ecr.eu-north-1.amazonaws.com/bar:v1.0

  job2:
    name: deploy_ec2
    needs: job1
    env:
      INSTANCE_KEY: ${{vars.INSTANCE_KEY}}
      PUBLIC_IP: ${{vars.PUBLIC_IP}}
      INSTANCE_KEY_B64: ${{ secrets.INSTANCE_KEY_B64 }}

    runs-on: ubuntu-latest

    steps:
      - name: deploy ec2 ssh
        run: |
          echo "$INSTANCE_KEY_B64"| base64 -d > EC2KeyDevOpsProject16062026
          chmod 400 EC2KeyDevOpsProject16062026
          ssh -i EC2KeyDevOpsProject16062026 -o StrictHostKeyChecking=no ec2-user@$PUBLIC_IP << EOF
            aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 547320736290.dkr.ecr.eu-north-1.amazonaws.com
            docker pull 547320736290.dkr.ecr.eu-north-1.amazonaws.com/bar:v1.0
            docker stop site || true
            docker rm site || true
            docker run -d -p 80:80 --name site 547320736290.dkr.ecr.eu-north-1.amazonaws.com/bar:v1.0
            docker ps

          EOF

          rm EC2KeyDevOpsProject16062026